config/routes.rb
# == Route Map
#

Rails.application.routes.draw do
  devise_for :admins, only: %i[session], controllers: { sessions: 'admins/sessions' }
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'

  namespace :admins do
    root 'dashboard#index'
    resources :dashboard, only: %w[index edit update]
  end
end

app/controllers/admins/dashboard_controller.rb
# frozen_string_literal: true

module Admins
  class DashboardController < Admins::BaseController
    before_action :set_order, only: %w[edit update]
    before_action :order_params, only: %w[index edit update]

    def index
      @orders = Order.includes(:user).all

      if params[:user_id].present? && params[:user_id].to_i.positive?
        @orders = @orders.where(user_id: params[:user_id])
      end

      if params[:status].present? && Order.statuses.keys.include?(params[:status])
        @orders = @orders.where(status: params[:status])
      end

      @orders = @orders.order(name: :desc)
    end

    def edit; end

    def update
      if order_params[:status].present? && Order.statuses.include?(order_params[:status])
        @order.update(status: order_params[:status])

        flash[:success] = 'Update success'
      else
        flash[:alert] = 'Update failed'
      end

      redirect_to admins_dashboard_index_path
    end

    private

    def order_params
      params[:order]
    end

    def set_order
      @order = Order.find_by(id: params[:id])

      if @order.blank?
        flash[:error] = 'Order is not found'
        redirect_to admins_root_path
      end
    end
  end
end

app/helpers/admins/dashboard_helper.rb
module Admins::DashboardHelper
  def user_order
    User.includes(:orders).pluck(:email, :id)
  end
end

app/views/admins/dashboard/edit.html.slim
.content
  = form_for @order, url: admins_dashboard_path, html: { class: 'form-vertical' }, method: :put do |f|
    .form-group Order Name: #{@order.name}
    .form-group User order: #{@order.user.email}
    .form-group
      = f.label :status
      = f.select :status, options_for_select(Order.statuses.keys, @order.status), {}, class: 'form-control'
    .form-group
      = f.submit 'Update', class: 'btn btn-primary'

app/views/admins/dashboard/index.html.slim
.content
  h2 List Order
  .filter-order
    = form_tag admins_dashboard_index_path, class: 'w-100', method: :get do
      .d-flex
        .form
          .form-group
            = select_tag :status, options_for_select(Order.statuses.keys, params[:status]), class: 'form-control', include_blank: 'All Status'
        .form.ml-5
          .form-group
            = select_tag :user_id, options_for_select(user_order, params[:user_id]), class: 'form-control', include_blank: 'All User'
        .col-lg-2.ml-auto.mr-3
          .form.text-right
            .form-froup
              = submit_tag 'Search', class: 'btn btn-primary'

  table.table.table-bordered
    tr
      th Name
      th User
      th Status
      th Action
    - if @orders.present?
      - @orders.each do |order|
        tr
          td = order.name
          td = order.user.email
          td = order.status
          td = link_to 'Edit', edit_admins_dashboard_path(order.id), class: 'btn btn-primary'