config/routes.rb
# == Route Map
#

Rails.application.routes.draw do
  devise_for :admins, only: %i[session], controllers: { sessions: 'admins/sessions' }
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'

  namespace :admins do
    root 'dashboard#index'
    resources :dashboard, only: %w[index edit update]
  end
end

app/views/layouts/_footer.html.slim
footer.nav.align-items-center.justify-content-center.justify-content-lg-start
  section
    .list-contact.w-100.d-flex
      .item.mr-5 Design by Dattq
      .item.mr-5 AlignTech Test
      .item.mr-5 Simple Project

app/views/layouts/_header.html.slim
header.header-custom
  .brand
    .brand__logo
      = image_tag 'svg/award.svg'
    span.brand__title TechAlign
  .nav.align-items-center.justify-content-center.justify-content-lg-start.mr-3
    = current_admin.email
    = link_to 'Logout', destroy_admin_session_path, method: :delete, class: 'btn btn-warning ml-3'

app/views/layouts/_sidebar_admin.html.slim
.sidebar-admin
  .sidebar-admin__content
    ul.nav.nav-pills.flex-column.mb-auto
      li
        = link_to 'Orders', admins_dashboard_index_path, class: 'nav-link'

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | AlignTech
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = yield

app/views/layouts/application_admin.slim
doctype html
html
  head
    title
      | AlignTech
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    - if flash.present?
      - flash.each do |type, msg|
        div.flash-error
          = msg
    header
      - if current_admin
        = render 'layouts/header'
    .body-container
      = render "layouts/sidebar_admin"
      .content-container
        = yield
        = render 'layouts/footer'